
version: 2.1

orbs:
    s3: aplazame/s3@0.0.14

jobs:
    build:
        docker:
        - image: aplazame/alpine:0.1.7-aws
        steps:
        - checkout

        - persist_to_workspace:
            root: ./
            paths:
            - banners
            - logos
            - images.css
            - index.html

workflows:
  version: 2
  deploy:
    jobs:
    - build

    - s3/deploy:
        requires:
        - build

        do_deploy:

        - s3/folder:
            bucket_name: cdn.aplazame.com
            src: logos
            dest: assets/logos

        - s3/folder:
            bucket_name: cdn.aplazame.com
            src: banners
            dest: assets/banners

        - s3/file:
            bucket_name: cdn.aplazame.com
            src: images.css
            dest: assets/images.css

        - s3/file:
            bucket_name: cdn.aplazame.com
            src: index.html
            dest: assets/index.html

        filters:
            branches:
                only:
                - master
