
version: 2.1

orbs:
    s3: aplazame/s3@0.0.15

jobs:
    build:
        docker:
        - image: aplazame/alpine:0.1.7-node
        steps:
        - checkout

        - run:
            name: npm install
            command: npm install
        - run:
            name: npm run build
            command: npm run build

        - persist_to_workspace:
            root: ./
            paths:
            - favicons
            - banners
            - logos
            - demo
            - images.css
            - index.html

workflows:
  version: 2
  deploy:
    jobs:
    - build

    - s3/deploy:
        requires:
        - build

        do_deploy:

        - s3/folder:
            bucket_name: cdn.aplazame.com
            src: favicons
            dest: assets/favicons
            cache_control: public, max-age:3600

        - s3/folder:
            bucket_name: cdn.aplazame.com
            src: logos
            dest: assets/logos
            cache_control: public, max-age:3600

        - s3/folder:
            bucket_name: cdn.aplazame.com
            src: banners
            dest: assets/banners
            cache_control: public, max-age:3600

        - s3/folder:
            bucket_name: cdn.aplazame.com
            src: demo
            dest: assets/demo
            cache_control: public, max-age:3600

        - s3/file:
            bucket_name: cdn.aplazame.com
            src: images.css
            dest: assets/images.css

        - s3/file:
            bucket_name: cdn.aplazame.com
            src: index.html
            dest: assets/index.html

        filters:
            branches:
                only:
                - master
